name: cicd
on:
  push:
    branches:
      - master
env:
  EC2_USER: 'ubuntu'
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SRC_PATH: 'build/libs/*.jar'
  DEST_DIR: '/home/ubuntu'
  APP_NAME: 'sboot'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: sboot
          POSTGRES_USER: sboot
          POSTGRES_PASSWORD: sboot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with Gradle
        run: chmod +x gradlew && ./gradlew test
      - name: save test reports as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/test
      - name: Build with Gradle
        run: ./gradlew build
      - name: save build artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: build-artifact
         path: build/libs/fullness-ec-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build/libs
    - name: Deploy to EC2 by SCP
      env:
        PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -t -o StrictHostKeyChecking=no -i private_key ${EC2_USER}@${EC2_HOST} "sudo mkdir -p ${DEST_DIR}/${APP_NAME} && sudo chmod -R 777 ${DEST_DIR}/${APP_NAME}"
        scp -i private_key build/libs/fullness-ec-0.0.1-SNAPSHOT.jar ${EC2_USER}@${EC2_HOST}:${DEST_DIR}/${APP_NAME}/app.jar
    - name: SSH EC2 Setup and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        envs: APP_NAME
        script: sudo systemctl restart $APP_NAME

